
- name: Conditions in playbook
  hosts: webserver
  # vars_files:
  #   - environments/{{env_name}}/group_vars/builddeploy.yml

  tasks:
      - name: Create users on worker node
        become: yes
        ansible.builtin.user:
          name: "{{item}}"
          state:  present
          groups: wheel
        loop:
          - "{{user1}}"
          - "{{user2}}"
      
      - name: check user is cretaed
        shell: "grep tomcatuser /etc/passwd"
        register: usersearchresult
        ignore_errors: yes

      - name: show user results
        debug: 
          msg: "Tomcat user not found. Hence aborting"
#        failed_when:
#          - usersearchresult.stdout == "" 

      - name: Install packages using yum
        become: yes
        yum:
          name: "{{item}}"
          state: present
          update_cache: yes
        loop:
          - tomcat
        when: 'ansible_distribution == "CentOS" and ansible_env.LOGNAME == "bofaansible" and ansible_distribution_version >= "7.5"'
